# Generated by Django 5.1.5 on 2025-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrcApp', '0002_course_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='SrcApp.course', verbose_name='Related Courses'),
        ),
    ]
