# Generated by Django 5.1.5 on 2025-01-28 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrcApp', '0005_remove_teacher_courses_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SrcApp.teacher'),
        ),
    ]
