# Generated by Django 5.1.5 on 2025-01-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SrcApp', '0006_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
