# Generated by Django 5.1.5 on 2025-01-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrcApp', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='', max_length=2000, verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='', max_length=200, verbose_name='Grade'),
        ),
    ]
