# Generated by Django 5.1.5 on 2025-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrcApp', '0009_student_faculty_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Course Duration(in weeks)'),
        ),
    ]
