# Generated by Django 5.1.5 on 2025-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrcApp', '0011_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='webcam_img',
            field=models.ImageField(null=True, upload_to='webcam_images', verbose_name='Webcam Image'),
        ),
    ]
